GET http://localhost:8000/uploads/
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQ1LCJlbWFpbCI6Imdhbmd3YXJzYXRlbmRyYS5rY210QGdtYWlsLmNvbSIsImlhdCI6MTc3NTgxNzA3MywiZXhwIjoxNzc1ODIwNjczLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.CQuWwQueEUeZsQcBXsmqFYKuBSMVSC7P8q94adO1wlM