GET http://localhost:8000/courses
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQ1LCJlbWFpbCI6Imdhbmd3YXJzYXRlbmRyYS5rY210QGdtYWlsLmNvbSIsImlhdCI6MTc3NTc5NjI1OSwiZXhwIjoxNzc1Nzk5ODU5LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.Qm_iI8h2ZQ_6tmJm9N1K01FB6wNVtH9aKa2-gYiqkB4
?limit=2
&page=1

GET http://localhost:8000/courses/1
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQ1LCJlbWFpbCI6Imdhbmd3YXJzYXRlbmRyYS5rY210QGdtYWlsLmNvbSIsImlhdCI6MTc3NTc5NjI1OSwiZXhwIjoxNzc1Nzk5ODU5LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.Qm_iI8h2ZQ_6tmJm9N1K01FB6wNVtH9aKa2-gYiqkB4