POST http://localhost:8000/auth/sign-in
Content-Type: application/json
{
    "email": "john@doe.com",
    "password": "Password@123"
}


POST http://localhost:8000/auth/sign-up
Content-Type: application/json
{
    "firstName": "Shivaan",
    "lastName": "Gangwar",
    "email": "gangwarsatendra.kcmt@gmail.com",
    "phoneNumber" : "+918979791676",
    "password": "Password@123"
}

POST http://localhost:8000/auth/refresh-tokens
