GET http://localhost:8000/email-templates
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImVtYWlsIjoiam9obkBkb2UuY29tIiwiaWF0IjoxNzc1NzE5NTQ3LCJleHAiOjE3NzU3MjMxNDcsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.slckUuvacB-s1IZL-K83rKqfJ3T4MT77ODpxisnjmXo


GET http://localhost:8000/email-templates/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImVtYWlsIjoiam9obkBkb2UuY29tIiwiaWF0IjoxNzc1NTY4NTk0LCJleHAiOjE3NzU1NzIxOTQsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.Jhw8CWIyCRVGU6tiTRkkOuNfUISwPps0cDL1xw-5Gis

GET http://localhost:8000/email-templates/by-name?name=welcome_email
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImVtYWlsIjoiam9obkBkb2UuY29tIiwiaWF0IjoxNzc1NTgwNzAyLCJleHAiOjE3NzU1ODQzMDIsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.4qvf5XVVOUcqZpXbaz2wFaZZltP9TLZwFR46P51_dww
