DELETE http://localhost:8000/email-templates/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImVtYWlsIjoiam9obkBkb2UuY29tIiwiaWF0IjoxNzc1NTY4NTk0LCJleHAiOjE3NzU1NzIxOTQsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.Jhw8CWIyCRVGU6tiTRkkOuNfUISwPps0cDL1xw-5Gis


DELETE http://localhost:8000/email-templates/2/permanent
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImVtYWlsIjoiam9obkBkb2UuY29tIiwiaWF0IjoxNzc1NTY4NTk0LCJleHAiOjE3NzU1NzIxOTQsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.Jhw8CWIyCRVGU6tiTRkkOuNfUISwPps0cDL1xw-5Gis